language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
script: python setup.py test
deploy:
  edge: true
  provider: pypi
  user: kageurufu
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: zapier/email-reply-parser
